  drop table clienti;
  
  create table clienti 
   (
	id number generated by default on null as identity,
	nome varchar2(50 byte), 
	cognome varchar2(50), 
	email varchar2(50), 
	indirizzo varchar2(100), 
	citta varchar2(50), 
	provincia varchar2(4), 
	cap number(8)
   ) ;
  
alter table clienti modify (id not null enable);
alter table clienti add constraint clienti_pk primary key (id);

Insert into clienti values (null,'Giuseppe','Verdi','gverdi@aol.com','Roncole Verdi','Busseto','PR','43011');
Insert into clienti values (null,'Gioacchino','Rossini','gioacchino@libero.it','Via del Duomo','Pesaro','PU','61122');
Insert into clienti values (null,'Giacomo','Puccini','gpuccini@gmail.com','Corte San Lorenzo, 9 ','Lucca','LU','55100');
Insert into clienti values (null,'Gaetano','Donizetti','gaetano@walla.com','Via Don Luigi Palazzolo, 88','Bergamo','BG','24122');
Insert into clienti values (null,'Vincenzo','Bellini','bellini@bellini.org','Piazza San Francesco d’Assisi, 3','Catania','CT','95100');
Insert into clienti values (null,'Antonio','Vivaldi','antonio.vivaldi@vivaldi.com','Rion del boh, 33','Venezia','VE','30100');
Insert into clienti values (null,'Domenico','Scarlatti','dscarlatti@mail.partenope.it','Rion del boh, 33','Napoli','NA','80100');
Insert into clienti values (null,'Claudio','Monteverdi','34566@libero.it','Piazza del Duomo, 1','Cremona','CR','26100');
Insert into clienti values (null,'Amilcare','Ponchielli','aponchielli@aol.com','Piazza Revellino, 3','Paderno Ponchielli','CR','26024');
Insert into clienti values (null,'Arcangelo','Corelli','acor@spalfans.it','Piazza Roma, 18','Fusignano','RA','48032');
Insert into clienti values (null,'Tommaso','Albinoni','albinoni@gmail.com','Via Roma','Castione della Presolana','BG','24020');
Insert into clienti values (null,'Giovanni Battista','Pergolesi','gbattista.draghi@jesimusiva.org','Piazza Ghislieri, 4','Jesi','AN','60035');
Insert into clienti values (null,'Vincenzo','Capecelatro','vin.cap@libero.it','Via Po, 22','Napoli','NA','80100');
Insert into clienti values (null,'Francesco','Cilea','fcilea@cilea.it','Via Cilea, 1','Palmi','RC','89015');
Insert into clienti values (null,'Arrigo','Boito','arrigob@aol.com','Via Cavour, 17','Padova','PD','35100');
Insert into clienti values (null,'Luigi','Cherubini','lcherubini@gmail.com','Via Ricasoli, 10','Firenze','FI','50100');
Insert into clienti values (null,'Giovanni Pierluigi','Da Palestrina','gpp@gmail.com','Via Cenreo, 2','Palestrina','RM','36');
Insert into clienti values (null,'Tarquinia','Molza','tarquinia@libero.it','Via Parma, 72','Modena','MO','41121');
Insert into clienti values (null,'Andres','Segovia Torres','andres.s@segovia.es','Villacarrillo, 133','Linares','JA','23700');

select count(*) from clienti;
